//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPerola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_chamadas
    {
        public int chamadasId { get; set; }
        public string titulo { get; set; }
        public string Resumo { get; set; }
        public string Texto { get; set; }
        public string UrlImagemPrincipal { get; set; }
        public string UrlImagemMini { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public System.DateTime DataAtualizacao { get; set; }
        public bool Ativo { get; set; }
    }
}
